version: '3.8'

services:
  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow_test
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: admin
      AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
      - ./utilits:/opt/airflow/utilits
    ports:
      - "8082:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
        airflow webserver --port 8080 & airflow scheduler
      "